// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydchmxfyostoonkocluo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkY2hteGZ5b3N0b29ua29jbHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDA1ODgsImV4cCI6MjA2NTgxNjU4OH0.bxZyQMciVqMJvzjp0akat3rI1mpsbXLTPXxpmZf-_yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);